version: 2
updates:

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - version-update

  - package-ecosystem: "npm"
    directory: "/examples/test-status-monitor"
    schedule:
      interval: "weekly"
    labels:
      - version-update