sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: true
node_js:
  - 10
  - 9
  - 8
before_install:
  - npm install -g npm@latest
before_script:
  - npm prune
script:
  - npm run test
after_success:
- npm run coveralls